### PR TITLE
implementation of a new JDBC connection pool.

### PR DESCRIPTION
**Pull request by hboumedane**

### CODE REVIEW

**Comment by cescoffier** [comment]
Wow, impressive work. Gonna have a look.

**Comment by hboumedane** [comment]
still not merged ?

**Comment by cescoffier** [comment]
Thanks !

**Comment by cescoffier** [comment]
Hum.... Nope:
http://jenkins.dynamis-technologies.com/job/Wisdom-JDBC/29/

Can you have a look ?

**Comment by hboumedane** [comment]
I will do that !! Boumedane homada
E-Mail : back_ahmed@yahoo.fr
 


     Le Vendredi 5 juin 2015 8h50, Clement Escoffier <notifications@github.com> a écrit :
   

 Hum.... Nope:
http://jenkins.dynamis-technologies.com/job/Wisdom-JDBC/29/Can you have a look ?—

**Pull request merged**
